version: "3"
services:
  plex:
    build: ./plex
    restart: unless-stopped
    ports:
      - "32401:32400"
      - "32401:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    environment:
      PLEX_FriendlyName: laverna
      PLEX_ManualPortMappingMode: 1
      PLEX_ManualPortMappingPort: 32401
      TZ: UTC
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data
