version: "3"
services:
  plex:
    build: ./plex
    restart: unless-stopped
    ports:
      - "32401:32400"
      - "32401:32400/udp"
    environment:
      PLEX_FriendlyName: laverna
      PLEX_ManualPortMappingMode: 1
      PLEX_ManualPortMappingPort: 32401
      TZ: UTC
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${DATA_DIR}/media:/data
  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    ports:
      - "8384:8384"
      - "22000:22000"
    volumes:
      - ${CONFIG_DIR}/syncthing:/var/syncthing/config
      - ${DATA_DIR}/sync:/var/syncthing/Sync
