version: "3.4"
services:

  home:
    build: ./home
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host: ${DOMAIN_NAME}"

  traefik:
    build: ./traefik
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CONFIG_DIR}/traefik:/config
    labels:
    - "traefik.enable=true"
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host: ${DOMAIN_NAME}; PathPrefixStrip: /traefik"

  duckdns:
    image: linuxserver/duckdns:latest
    restart: unless-stopped
    environment:
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${DUCKDNS_TOKEN}
      TZ: UTC

  plex:
    build: ./plex
    restart: unless-stopped
    ports:
    - "32401:32400"
    - "32401:32400/udp"
    environment:
      PLEX_FriendlyName: laverna-local
      PLEX_ManualPortMappingMode: 1
      PLEX_ManualPortMappingPort: 32401
      TZ: UTC
      VERSION: latest
    volumes:
    - ${CONFIG_DIR}/plex:/config
    - ${MEDIA_DIR}:/data
    labels:
    - "traefik.enable=true"
    - "traefik.port=32400"
    - "traefik.frontend.rule=Host:plex.${DOMAIN_NAME}"

  syncthing:
    build: ./syncthing
    restart: unless-stopped
    hostname: laverna
    healthcheck:
      disable: true
    environment:
      STNODEFAULTFOLDER: "true"
      LISTEN_PORT: "22001"
    ports:
    - "22001:22001"
    volumes:
    - ${CONFIG_DIR}/syncthing:/config
    - ${SYNC_DIR}:/data
    labels:
    - "traefik.enable=true"
    - "traefik.port=8384"
    - "traefik.frontend.rule=Host: ${DOMAIN_NAME}; PathPrefixStrip: /syncthing/"

  sonarr:
    build: ./sonarr
    restart: unless-stopped
    environment:
      URL_BASE: sonarr
      TZ: UTC
    volumes:
    - ${CONFIG_DIR}/sonarr:/config
    - ${MEDIA_DIR}/tv:/tv
    - ${DOWNLOAD_DIR}:/downloads
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host: ${DOMAIN_NAME}; PathPrefix: /sonarr/"

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      TZ: UTC
    volumes:
    - ${CONFIG_DIR}/sabnzbd:/config
    - ${MEDIA_DIR}/tv:/tv
    - ${DOWNLOAD_DIR}/sabnzbd-complete:/downloads
    - ${DOWNLOAD_DIR}/sabnzbd-incomplete:/incomplete-downloads
    labels:
    - "traefik.enable=true"
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host: ${DOMAIN_NAME}; PathPrefixStrip: /sabnzbd/"
